version: '3.9'
services:
  mysql:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./dbfiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chatForumDB
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-padmin"]
      timeout: 20s
      retries: 10

  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      node:
        condition: service_started
    stdin_open: true
    tty: true
